### ISSUE TITLE
The split of Cora is different from the original setting

### ISSUE THREAD

**Issue by wzfhaha** [kavehhassani/mvgrl#2]
Dear authors, 
    I have noticed that you use DGL to load Cora dataset. But the corresponding data split is not the correct split used in GCN paper. And someone has already pointed out this issue (https://github.com/rusty1s/pytorch_geometric/issues/891). Thus your comparison with baselines on Cora dataset is invalid.

**Comment by WxTu** [comment]
Dear authors,
I have also noticed the case stated by wzfhaha. Could you give an explanation for the discrepancy?

**Comment by kavehhassani** [comment]
We didn't know at the time about this issue. We simply used DGL dataloader to reduce the amount of coding and didn't know they had this issue.
