### ISSUE TITLE
“Kill” problem when I ran the REDDIT-BINARY and REDDIT-MULTI datasets

### ISSUE THREAD

**Issue by ha-lins** [kavehhassani/mvgrl#3]
Hi @kavehhassani,

Thanks for the nice work and your released code. 

I met a "kill" problem by the os when I loaded these two big datasets. It is caused by the huge memory usage (100G+) of this [for loop](https://github.com/kavehhassani/mvgrl/blob/master/graph/dataset.py#L145). Could you give me some advice? 

Thanks in advance!

**Comment by kavehhassani** [comment]
You should tweak the code base on your memory budget: subsampling is one way to address it.
