### ISSUE TITLE
A small problem in the code

### ISSUE THREAD

**Issue by mgf9505** [kavehhassani/mvgrl#5]
Dear authors,
   I notice that the code  "adj = normalize_adj(adj + sp.eye(adj.shape[0])).todense()" at line 64 of the path "node/dataset.py" has already added the self-loop. But it adds the self-loop again at line 62 of the path "utils.py".

**Comment by kavehhassani** [comment]
Ah thanks for catching that, although I don't think it can have a big impact on the behavior.
