### ISSUE TITLE
Efficience on large graph

### ISSUE THREAD

**Issue by junkangwu** [kavehhassani/mvgrl#6]
I'm interested in self-supervised learning on the graph and `mvgrl` is an excellent work that combining self-supervised learning with multi-view augmentation. However, I'm also curious about its usage in large graphs such as knowledge graph. May I ask you about the suggestion or efficient training method on the augmentation operation on the knowledge graph? Because in the way of `mvgrl` , it needs 4 GNN encoders at the same time per epoch. I try to experiment with it but it's extremely time-consuming.
Thanks a lot in advance~

**Comment by kavehhassani** [comment]
Well, you can always sub-sample the graph to sub-graphs and do the learning on random sub-samples. It is very similar to random cropping of images in computer vision.
